// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmT8IAyYVN9Y5NsX6ZnxW0iyS_77XQV4U',
    appId: '1:116064829037:web:0f09a23f648f6d9c1c8964',
    messagingSenderId: '116064829037',
    projectId: 'buddies-proto',
    authDomain: 'buddies-proto.firebaseapp.com',
    storageBucket: 'buddies-proto.appspot.com',
    measurementId: 'G-QV72CZF508',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXzS5q7PUFiJzDQEFLFWjmfxdgDQdIx0',
    appId: '1:116064829037:android:713e7081547c13aa1c8964',
    messagingSenderId: '116064829037',
    projectId: 'buddies-proto',
    storageBucket: 'buddies-proto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_aIcNggggpWoTO4-247SYZItFsb2a4M',
    appId: '1:116064829037:ios:14eba1ed77dc00891c8964',
    messagingSenderId: '116064829037',
    projectId: 'buddies-proto',
    storageBucket: 'buddies-proto.appspot.com',
    iosBundleId: 'com.example.buddiesProto',
  );
}
